### ISSUE TITLE
Unable to turn interact that have additional ace functionality and remove them

### ISSUE THREAD

**Issue by Mercer01** [acemod/ACEX#118]
Currently tested objects affect:
- Chairs (Land_CampingChair_V2_F)
- Lamps (Land_PortableLight_double_F)

If you place one of these objects using Fortify and then try to interact with them e.g. to Sitdown or turn off and on the light, the "Remove Object" option and the other ace option.

**Workaround**
If you move further away from the object the Fortify remove option is avalible at a greater distance so you can remove the item

**Comment by Dystopian** [comment]
It looks quite strange to fortify with chairs and lamps.

As for problem it's not enough just to move `Remove` action to `ACE_MainActions` submenu because its default distance is only 2m and it's not enough for big walls/buildings. There should be some workaround like `ace_interaction_fnc_getVehiclePos` or acemod/ACE3#3342.
